#!/bin/bash

# specify the case you want to test here!
case=case1
version=advanced
# version=advanced
# Build and run your final project!
#! warning! 最後面的make有多一行用來compile include folder裡面的東西
NTHU_bike:
	g++ -g -std=c++11 -o ./bin/main ./src/*.cpp 
	./bin/main $(case) $(version)
